CREATE TABLE ACCOUNTUSERS (
    ACCOUNTUSERS_ID INTEGER PRIMARY KEY,
    ACCOUNTUSERS_USERNAME VARCHAR2(25),
    ACCOUNTUSERS_PASSWORD VARCHAR2(25),
    ACCOUNTUSERS_SUPERUSER NUMBER(1) DEFAULT 0
);
/

CREATE TABLE BANK_ACCT (
    BANK_ACCT_ID INTEGER PRIMARY KEY,
    BANK_ACCT_BALANCE NUMBER(8,2) DEFAULT 0.00,
);
/

CREATE TABLE TRANSACTIONS (
    TRANSACTIONS_ID INTEGER PRIMARY KEY,
    TRANSACTIONS_TIME DATE,
    TRANSACTIONS_TYPE VARCHAR2(20),
    TRANSACTIONS_MODIFIER NUMBER(8,2) DEFAULT 0.00
);
/

CREATE TABLE ACCOUNTUSERS_BANK_ACCT (
    ACCOUNTUSERS_ID INTEGER,
    BANK_ACCT_ID INTEGER,
    PRIMARY KEY (ACCOUNTUSERS_ID, BANK_ACCT_ID)
);
/

CREATE TABLE BANK_ACCT_TRANSACTIONS (
    BANK_ACCT_ID INTEGER,
    TRANSACTIONS_ID INTEGER,
    PRIMARY KEY (BANK_ACCT_ID, TRANSACTIONS_ID)
);
/

--FOREIGN KEY CONSTRAINS (DDL)
ALTER TABLE ACCOUNTUSERS_BANK_ACCOUNT
ADD CONSTRAINT FK_AU_AU_BANK_ACCOUNT
FOREIGN KEY (ACCOUNTUSERS_ID) REFERENCES ACCOUNTUSERS(ACCOUNTUSERS_ID);
/

ALTER TABLE ACCOUNTUSERS_BANK_ACCT
ADD CONSTRAINT FK_BANK_ACCT_AU_BANK_ACCT
FOREIGN KEY (BANK_ACCT_ID) REFERENCES BANK_ACCT(BANK_ACCT_ID);
/

ALTER TABLE BANK_ACCT_TRANSACTIONS
ADD CONSTRAINT FK_BANK_ACCT_BANK_ACCT_TRANS
FOREIGN KEY (BANK_ACCT_ID) REFERENCES BANK_ACCT(BANK_ACCT_ID);
/

ALTER TABLE BANK_ACCT_TRANSACTIONS
ADD CONSTRAINT FK_TRANS_BANK_ACCT_TRANS
FOREIGN KEY (TRANSACTIONS_ID) REFERENCES TRANSACTIONS(TRANSACTIONS_ID);
/

ALTER TABLE BANK_ACCT
ADD CONSTRAINT FK_TRANSACTIONS_ID
FOREIGN KEY (TRANSACTIONS_ID) REFERENCES TRANSACTIONS(TRANSACTIONS_ID);
/

CREATE SEQUENCE SQ_ACCOUNTUSERS_PK
START WITH 1 
INCREMENT BY 1;
/


CREATE SEQUENCE SQ_BANK_ACCT_PK
START WITH 1 
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_TRANSACTIONS_PK
START WITH 1 
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_ACCOUNTUSERS
BEFORE INSERT ON ACCOUNTUSERS
FOR EACH ROW
BEGIN
    SELECT SQ_ACCOUNTUSERS_PK.NEXTVAL INTO :NEW.ACCOUNTUSERS_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_BANK_ACCT
BEFORE INSERT ON BANK_ACCT
FOR EACH ROW
BEGIN
    SELECT SQ_BANK_ACCT_PK.NEXTVAL INTO :NEW.BANK_ACCT_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_TRANSACTIONS
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
    SELECT SQ_TRANSACTIONS_PK.NEXTVAL INTO :NEW.TRANSACTIONS_ID FROM DUAL;
END;
/

--POPULATING LISTS

INSERT INTO ACCOUNTUSERS(ACCOUNTUSERS_USERNAME, ACCOUNTUSERS_PASSWORD,ACCOUNTUSERS_SUPERUSER)
VALUES('Kevin','password',1);

INSERT INTO ACCOUNTUSERS(ACCOUNTUSERS_USERNAME, ACCOUNTUSERS_PASSWORD,ACCOUNTUSERS_SUPERUSER)
VALUES('Tad','password2',1);

SELECT * FROM ACCOUNTUSERS;

INSERT INTO BANK_ACCT(BANK_ACCT_BALANCE)
VALUES(300000.00);